name: ktbthon
services:
  backend:
    build:
      context: ./EARS_TO_WORLD_BE
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - ktb_network
    ports:
      - "8080:8080" #서버
      - "5005:5005" #디버깅
    restart: always
  frontend:
    depends_on:
      - backend
    build:
      context: ./EARS_TO_WORLD_FE
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - ktb_network
  nginx:
    image: nginx:latest
    build:
      context: ./EARS_TO_WORLD_BE/nginx
    container_name: nginx
    networks:
      - ktb_network
    restart: always
    volumes:
      - ./EARS_TO_WORLD_BE/nginx/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
networks:
  ktb_network:
    driver: bridge
