name: earstoworld

services:
  backend:
    image: suh021/earstoworld:latest
    container_name: backend
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - ktb_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html  # React 빌드 결과를 Nginx에 연결
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ktb_network
    restart: always

networks:
  ktb_network:
    driver: bridge